sudo: required
language: go

go:
  - 1.11.x

script:
  - make buildlocal

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
