sudo: required
language: go

go:
  - 1.11.x

script:
  - GOOS=darwin GOARCH=amd64 go build -o ./kubectl-pvcexec ./main.go

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
